### ISSUE TITLE
[docs suggestion] adding docs detailing for API change in 0.8.2 -> 0.8.3

### ISSUE THREAD

**Issue by j9ac9k** [mherrmann/fbs#124]
I was about to open an issue for not being able to `fbs run`, or `fbs freeze` as with 0.8.3; but after looking at the commit history for between 0.8.2 I realized there was an API change.

While before, I was able to run

```python
from fbs_runtime.application_context import ApplicationContext, cached_property
```

I now need to run

```python
from fbs_runtime.application_context.PySide2 import ApplicationContext, cached_property
```

Not a particularly big deal, and the docs on the webpage are updated accordingly (thanks for that btw!) but as this application follows semantic versioning, an API breakage was introduced as a patch version change is problematic.

This is purely a suggestion, but I would consider re-adding `README.md`, if anything just to provide a link to the documentation, and ideally a note about an API breaking change that was introduced so that individuals aren't caught off guard as I was.

As per usual, thanks for creating and maintaining this awesome tool, it's made my deployments substantially easier.

**Comment by mherrmann** [comment]
Thank you for the suggestion / idea, and sorry for the trouble with the breaking change.

For now, I take the liberty to make breaking changes to fbs without notice. The reason is that fbs is still (comparatively) young, and this freedom enables me to improve it more quickly. Once fbs's user base has grown larger, it will make sense to have a more stable (but heavier) approach.

To compensate for this, I actually make quite an effort to document all changes on the [Releases page](https://github.com/mherrmann/fbs/releases). In particular, for the breaking change you encountered, it [says](https://github.com/mherrmann/fbs/releases/tag/v0.8.3):

> This is a backwards-incompatible release. To upgrade to it, replace the following import:
> 
>    from fbs_runtime.application_context import ApplicationContext
> 
> by one of the following two:
> 
>    from fbs_runtime.application_context.PyQt5 import ApplicationContext
>    from fbs_runtime.application_context.PySide2 import ApplicationContext

So when upgrading to a new version of fbs, I recommend looking at the Releases page to see if your code might be affected by any of the changes. I guess I could make the Releases page more prominent. But to be honest, I think it's a pretty canonical place for documenting changes. So instead of burying a link to this page in the docs that hardly anyone will ever stumble upon, I'll rely on people's ability to read the commit history (like you) or hopefully the easier approach of checking the Releases.

**Comment by j9ac9k** [comment]
No need to apologize, thanks for open sourcing this awesome library, I totally get having to make breaking changes due to its infancy.

I have no clue how I missed the releases page, I didn't know that was a thing, and as you point out, it contains the relevant information there.  Thanks for sharing and updating it.

Also completely unrelated, but I verified `fbs` works with pyside2 5.12.4 the other day.

**Comment by mherrmann** [comment]
> Also completely unrelated, but I verified fbs works with pyside2 5.12.4 the other day.

That's good to know / hear. Thanks!
