### ISSUE TITLE
Passing arguments to pyinstaller

### ISSUE THREAD

**Issue by RyanSchaefer** [mherrmann/fbs#131]
I know this was mentioned in #21, but the language in that issue is really vague about how exactly an individual is suppose to pass the arguments.

I specifically wanted to pass the arguments `--onefile` and `--noconsole` and I could see that there was an area available in the source for extra arguments to pyinstaller, but I couldn't figure out how to utilize it.

Would it be possible to add this to the tutorial or get an explanation of how I am suppose to use it?

Thank you!

**Comment by mherrmann** [comment]
Before I answer your question: I'm surprised you need to pass `--noconsole`. Normally, you shouldn't get a console window. Which platform are you on?

Regarding `--onefile`: I advise not to use it. fbs's features such as [resource files](https://build-system.fman.io/manual/#resource-files) and [build settings](https://build-system.fman.io/manual/#public_settings) likely won't work with `--onefile`. Also, `--onefile` has a big performance penalty: Every time your application starts, PyInstaller first extracts all files to a temporary directory. This increases startup time. In my eyes, these disadvantages greatly outweigh the very very superficial benefit of having "a single .exe".

**Comment by RyanSchaefer** [comment]
So just on my virtual environment I think it is important to mention that I am using PyAutoGUI and Selenium. Besides that I am on windows 10.

![image](https://user-images.githubusercontent.com/12058253/61722901-b6e4e380-ad30-11e9-9b66-2053705ec1e6.png)

![image](https://user-images.githubusercontent.com/12058253/61722951-d4b24880-ad30-11e9-8948-5b26bdd53ffe.png)

I tried suppressing the logging of selenium as much as possible but there is still a logging message that is output as soon as the script is run. So I am not sure what the issue might be. 

I can't build an installer because I am on a managed machine where the path cannot be changed on a machine wide basis and I can only edit my user path which prevents me from using NSIS. So I don't know if that would cause the application to run without a console appearing. Also, that is why I wanted to use the `--onefile` option, for increased portability when distributing this tool.

**Comment by mherrmann** [comment]
I once had similar issues (a console window popping up / the console being "hijacked") when I was using Selenium with chromedriver. Could that be the issue?

I understand your use case for `--onefile` better now. But I'm afraid it is as I said above: Many of fbs's features rely on you not using this flag. I believe the lesser evil is to avoid it. Maybe you could, on the first run, ask the user "do you want to add an entry for <your app> to the start menu"? This should be possible without any special permissions.

Regarding the console, I would check if the console window also appears for the simple app from [fbs's tutorial](https://github.com/mherrmann/fbs-tutorial). If yes, I'd say it's a bug in fbs. Otherwise, it's something to do with your setup, and as I said I'd suspect it to be chromedriver then.

**Comment by RyanSchaefer** [comment]
Yeah that is what this is. I did an example where it was just 

```
from selenium import webdriver

b = webdriver.Chrome()
```

and installed it with pyinstaller --noconsole but the console still appeared. This is an issue with selenium.

**Comment by mherrmann** [comment]
Then a shameless plug for [Helium](https://heliumhq.com), another project I'm involved with. It wraps around Selenium to give you a much nicer API. It's available for Python and Java. But it is a commercial project with a 30 day trial.
