### ISSUE TITLE
Support for PyInstaller 3.6

### ISSUE THREAD

**Issue by hanson2010** [mherrmann/fbs#188]
Yes. Pyinstaller has updated its hooks file. But the latest fbs 0.8.6 depends on PyInstaller==3.4.

**Comment by cisba** [comment]
There is the [CVE-2019-16784](https://github.com/pyinstaller/pyinstaller/security/advisories/GHSA-7fcj-pq9j-wh2r) issue too.

Ok, it is not actually a security issue for fbs because pyinstaller is not used in a "one-file" mode.

However in february github sent me an email:

> We found a vulnerable dependency in a repository you have security alert access to.
> @TimeBags	TimeBags/timebags
> Known high severity security vulnerability detected in PyInstaller < 3.6 defined in requirements.txt.
> You have automated security updates enabled, so we are attempting to create a pull request to update the vulnerable dependency.

**Comment by scarygliders** [comment]
Security issues aside, I am hitting the error where some important files are not being copied over to the target directory when issuing a "fbs freeze" in my PySide2 application.

Namely, QtWebEngineProcess.exe and 4 other associated files.

It would be nice if fbs utilised a more up to date PyInstaller version, if said version has sorted out the problem for users of PySide2.

**Comment by HalfWhitt** [comment]
Just chiming in as another squeaky wheel. I thought I'd check out fbs as a potentially nicer alternative to straight PyInstaller. Unfortunately I've been completely unable to get it to work, despite downgrading to Python 3.6.7, testing out several older versions of PySide (back to the 5.11.0, the oldest version pip has available for me), and attempting manual patches to PyInstaller 3.4 to squash the bugs. It looks like a cool package, and I'd like to try using it when possible.

**Comment by breisfeld** [comment]
Sadly, I am in the same boat. 

I had set up my project in accord with the recommended fbs procedures and was very hopeful because `fbs run` worked perfectly for my application.

Unfortunately, when I got ready to develop an installation package, `fbs freeze` did not work, apparently owing to package version incompatibilities.

I tried various fixes to files within PyInstaller, but nothing worked.

So, despite the promise of fbs, I am back to seeking other options.

**Comment by jprouty** [comment]
@breisfeld I feel the same way. If you're interested in getting off the fbs train, I just did it on my project and am using pyinstaller directly, which has been working flawlessly on python 3.8! I have a few shell scripts that do the release per platform. [Take a look](https://github.com/jprouty/mint-amazon-tagger/tree/master/release).

**Comment by breisfeld** [comment]
Thank you for sharing the links to your scripts!

**Comment by jprouty** [comment]
My pleasure! It's really not too involved once you get into it. Note, for windows, I am not making an installer, just the executable for the time being.

**Comment by breisfeld** [comment]
Very nice automation scripts! 
I don't want to take away anything from `fbs` or 'pyinstaller`, which are very impressive packages, but for my application, I am now finding that `pynsist` (https://github.com/takluyver/pynsist) is a better fit.

**Comment by Timtam** [comment]
PyInstaller 4.0 is out already, and GitHub still reminds me of the security issue when using the latest version of fbs in my projects. Any hope to get an update for fbs which works with a more recent version of PyInstaller soon?

**Comment by Kranzes** [comment]
Ahem, is there any update on this issue? PyInstaller 4.3 is already out.

**Comment by mherrmann** [comment]
[fbs Pro](https://build-system.fman.io/pro) supports the latest PyInstaller versions.

**Comment by Kranzes** [comment]
Paid software? ill skip on that one.

**Comment by mherrmann** [comment]
@Kranzes you may find this blog post enlightening: https://fman.io/blog/dear-comrade/

**Comment by Timtam** [comment]
Feeling the same here. Having no problem with people wanting to get paid for their work, really. Doing that via support for newer version of software that you can decide on using is file (like newer Qt versions or Python versions, as long as the ones supported in the free version are still supported by the developers). But not supporting newer PyInstaller versions, while the current one is classified as a security issue by GitHub, so that you cannot (!) release an open-sourced product on GitHub that uses the latest free version of fbs because it will get security flags due to PyInstaller 3.4 being used is just a no go in any way possible.
Not speaking about the fact that you cannot publish any open-sourced product with the paid version because other people cannot check it out without having to pay on their own, they cannot even set it up. I could probably work with that issue, but security issues in a public version that you're expecting people to use and saying "to resolve this security issue you need to pay me" is just not happening.
And no, when using systems like Pipenv, you cannot manually upgrade to a newer PyInstaller version, although it would theoretically work. Pipenv will continually complain about version mismatches here.
Starting to migrate from fbs for that reason. Newer versions of Python and QT when paying? Sure. Having to live with security issues? Nope, thanks.

**Comment by mherrmann** [comment]
Yes, please move on @TimTam. Then you'll get what you paid for: nothing. And if your time as a developer isn't worth the cheap license price, then I welcome you to spend the many hours it will take to do things on your own. I have zero responsibility towards you. And I don't like freeloaders. So yes, that's fantastic. Please, do move on. You will not be missed here.

**Comment by Kranzes** [comment]
> @Kranzes you may find this blog post enlightening: https://fman.io/blog/dear-comrade/

I Highly disagree with what you said here: "But in a world where everything is free, we are the product. It's a world where big corporations have all the power because they are the only ones who can afford to offer "free" services.".
literally all the software tools that actually matter in the world are: Free/Open-Source/FOSS, they always were, even from the start when the dev was doing it without getting paid, and even now that the entire world uses that piece of software/tool **Its still Free/Open-Source/FOSS.** You are not the product when the software is under a reasonable license.

Paid services/official support from the author of the software are Fairly reasonable, but fbs offers is not a service that requires spending big amount of money on the infrastructure and servers, Its a standalone tool, You aren't even the one paying for the hosting of the tool, Its literally Microsoft which owns Github. All people wanted was to essentially update the python version which is used for fbs, which to be honest, is not very hard since there aren't any backward comparability issues between the current/updated version. 

Also lets go back to the "You are the product" statement, lets say i host my FOSS software on Github.com for free, How am i the product? I get free hosting for my software as long as its not anything illegal.

Do you really think Linus Torvalds was struggling to feed himself when he wasn't getting any money for the ton of work he put into developing the Linux kernel and Git, (which by the way you are currently using)? Linus also does not charge anything to use "His" software which has over a million GIt commits.

**Comment by Kranzes** [comment]
> Yes, please move on @Timtam. Then you'll get what you paid for: nothing. And if your time as a developer isn't worth the cheap license price, then I welcome you to spend the many hours it will take to do things on your own. I have zero responsibility towards you. Not for security fixes, or for anything else. And I don't like freeloaders. So yes, that's fantastic. Please, do move on. You will not be missed here.

No one will miss fbs either since it has literally been outdated for over 3+ years. heh :^)

By the way im sure telling people to F off will be great for your PR, once you finally get a job as a software developer and your employer will check out your Github account :woozy_face:

**Comment by Kranzes** [comment]
> Yes, please move on @Timtam. Then you'll get what you paid for: nothing. And if your time as a developer isn't worth the cheap license price, then I welcome you to spend the many hours it will take to do things on your own. I have zero responsibility towards you. Not for security fixes, or for anything else. And I don't like freeloaders. So yes, that's fantastic. Please, do move on. You will not be missed here.

We are very well aware that fbs (free) is under a FOSS license which means it does not have any warranty and the author isn't responsible for anything, We didnt demand you to update the code, we asked kindly but you decided that the best move in this situation is to tell us to flip off.

**Comment by mherrmann** [comment]
If you think it's easy to keep compatibility with new Python versions @Kranzes then you are welcome to fork fbs and make the fixes. As a capitalist, this discussion is not worth my (significant) hourly rate. Closing it now.
