### ISSUE TITLE
fbs freeze throws AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by bicarlsen** [mherrmann/fbs#236]
**Note:** This is an issue with `PyInstaller` not `fbs`, but it seemed relevant to the community, so I wanted to share it here.

The issue is addressed in [Issue #5540 of PyInstaller](https://github.com/pyinstaller/pyinstaller/issues/5540), and is resolved by [**bwoodsend**'s 5540 patch](https://github.com/bwoodsend/pyinstaller/commit/589819183afc18f2d5b51dbbce68b7aca020c5e8).

**Comment by mherrmann** [comment]
Thank you for sharing!

**Comment by Kastakin** [comment]
The problem seems to be relevant only on Arch-Linux machines due to a glibc incompatibility. On Windows, Mac or Ubuntu the issue doesn't appear to be relevant. I have a GitHub Actions based pipeline to compile installers for the aforementioned OSs as targets and the runners complete their jobs without any issues.

As a workaround on my local machine I had to download the last source for PyInstaller, manually edit the paackage version to `3.4` since is the highest version supported by `fbs` that doesn't throw an error when running `fbs freeze` and then in the virtual environment uninstall `pyinstaller` and installing the locally modified version in exchange.

It's not pretty but it works for the time being... @mherrmann  What are the main issues that limit the possibility to use newer releases of the `pyinstaller` packages? I might look into it and make a pull request for it if it's something I can help with!

**Comment by bicarlsen** [comment]
@Kastakin , I’m on Ubuntu 21 and got this error, too.

**Comment by Kastakin** [comment]
> @Kastakin , I’m on Ubuntu 21 and got this error, too.

My Github Runner is running on `Ubuntu-18.04` to have an higher compatibility, it probably still runs an older version of `glibc`. Thanks for pointing it out!

**Comment by bicarlsen** [comment]
> > @Kastakin , I’m on Ubuntu 21 and got this error, too.
> 
> My Github Runner is running on `Ubuntu-18.04` to have an higher compatibility, it probably still runs an older version of `glibc`. Thanks for pointing it out!

I believe the change occured with Ubuntu 21, my Ubuntu 20  machine seems to be fine.
