### ISSUE TITLE
License model in README not compatible with LICENSE

### ISSUE THREAD

**Issue by hansfilipelo** [mherrmann/fbs#30]
First: 

 - I am not looking to use fbs in a closed source and/or commercial product.
 - I am not a lawyer or a person with any form of deep knowledge within any legal system. 

I am merely a developer who finds fbs interesting and is looking to create a small (FOSS)  project using fbs.

--------------------

The license of fbs is said to be GPL (version 3), however, the README states that: 

    In simple terms, this means you can use it for free in open source projects that are also licensed under the GPL. If on the other hand you want to use the project for a proprietary app where you don't want to open source the code, then you need a commercial license. The price for one developer is currently EUR 249. One year of updates is included. To obtain a license, click here.

It is to my understanding that the license GPL  means that one can not redistribute a version of the software without also providing the source code for the modifications made to the software under GPL. This would mean that: 

- Using fbs to ship another software does not mean that you need to provide the source of your application, but rather that you need to redistribute the changes you've made to fbs under the GPLv3 license. 

I suggest that the author change the license of fbs into a license compatible with his vision within the README, since GPLv3 to my knowledge is not compatible with said vision. 

Regards,

Hans-Filip

**Comment by hansfilipelo** [comment]
I'll add this link: 

https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#fulltext

**Comment by mherrmann** [comment]
Thank you for the input. What you describe sounds to me a lot like the *L*GPL. The difference between the two is that under the GPL, also software that _links to_ GPL'd work falls under the GPL. This applies to fbs, because to use it you add `from fbs_runtime import ...` to your code. This makes your code fall under the GPL as well, and so you must also make your code public. In other words, your conclusion that you do not need to provide your source code is, in my eyes, false.

**Comment by hansfilipelo** [comment]
> Thank you for the input. What you describe sounds to me a lot like the _L_GPL. The difference between the two is that under the GPL, also software that _links to_ GPL'd work falls under the GPL. This applies to fbs, because to use it you add `from fbs_runtime import ...` to your code. This makes your code fall under the GPL as well, and so you must also make your code public. In other words, your conclusion that you do not need to provide your source code is, in my eyes, false.

Consider a `main.py`-file from fbs with the following additions:

`
import myexternalclosedsourcelib

myexternalclosedsourcelib.doStuff()
`

The code contained within `myexternalclosedsourcelib` is not derrivative of fbs since its code does not depend on fbs in any way (by linkage or function) and hence it is not breaking GPL to not release `myexternalclosedsourcelib` as GPL. 

The modified `main.py` (part of the modified distribution of fbs, which itself is under GPL) does however depend on `myexternalclosedsourcelib`. Again, not releasing `myexternalclosedsourcelib` is in my view not a violation of GPL. If that were the case relying on "Windows 10 SDK" for fbs itself would be a violation of GPL.

**Comment by hansfilipelo** [comment]
To further add to the discussion:

- Which means that including `myexternalclosedsourcelib` with an fbs distribution is not in violation of GPL. One impact of the opposite ist that GNU/Linux distributions could not ship with proprietary binaries.

**Comment by mherrmann** [comment]
I still don't get the point. Yes, you wouldn't have to open source libraries which you use in fbs projects. But you would have to open source your own code. That is what I intend, and what I mean by the text in the README. How is that violated?

**Comment by mherrmann** [comment]
Ah I think I see your point now. You could implement your entire app in `myexternalclosedsourcelib`, then simply link to it from fbs(?)

**Comment by hansfilipelo** [comment]
> Yes, you wouldn't have to open source libraries which you use in fbs projects. But you would have to open source your own code. 

The point here is that `myexternalclosedsourcelib` IS my own code.

**Comment by mherrmann** [comment]
Thank you very much for raising this @hansfilipelo. As you noticed, I didn't get it at first. But I do believe you have a point. Now you are here (and I know you're capable, even though you're not a lawyer): Do you think it would work if I just said "you can use fbs under the GPL **for non-commercial purposes**"?

**Comment by gbtami** [comment]
@mherrmann if you want licensing fbs similar to PyQt these links may help:
https://www.riverbankcomputing.com/commercial/pyqt
https://www.riverbankcomputing.com/commercial/license-faq

**Comment by hansfilipelo** [comment]
Googling "non commercial open source license" gives this: https://opensource.org/licenses/NPOSL-3.0

**Comment by hansfilipelo** [comment]
@gbtami fbs is currently licensed under GPL (as PyQt). The issue for fbs is that while PyQt is a framework on which software depend (hence derive from), fbs instead packages independent software into a distribution.

**Comment by mherrmann** [comment]
Thank you both. I asked on [StackOverflow](https://opensource.stackexchange.com/questions/7397/restrict-gplv3-to-non-commercial-use/7399#7399) and got a very interesting reply. If you search for "plugin" and "interpreter" there, you will find very interesting stances there. In essence, I believe they imply that the loophole you described @hansfilipelo does not work because `myexternalclosedsourcelib` implicitly relies on fbs, in particular the `QApplication`.

**Comment by mherrmann** [comment]
I'm sorry, I'm afraid I (again) don't fully understand your example. Do I assume correctly that in your scenario, `closedsourcethirdpartylib` depends on PyQt, but not on fbs?

As a side note, what you wrote above is not entirely correct:

> fbs instead packages independent software into a distribution.

It also _runs_ your application. In other words, parts of fbs are contained in the binary package produced by fbs. These parts thus become an integral part of your application.

Let me call the issue you are describing "loophole". I know you don't mean it that way - you are more concerned about the legal ramifications for other libraries. But from fbs's perspective that's where the threat lies.

Let me re-iterate the loophole and then explain why I think it fails. Using your idea, one could split an application based on fbs into two parts: A single file, `main.py`, that references `fbs_runtime`. And a `library` that is imported by `main.py` and contains the implementation of the application, but no (explicit) reference to fbs. Your point was that `library` cannot fall under fbs's GPL requirements because it doesn't even "know" about fbs. Because otherwise, taking this to an extreme, _any_ third-party library that is shipped as part of an fbs-based application would be subject to fbs's GPL constraints.

The distinction in my eyes is that some libraries will "know" about fbs, while others will not. For example, the popular `requests` Python library for sending HTTP requests might be packaged as part of an fbs app, but is clearly independent of fbs. Also other libraries, even when based on PyQt to draw widgets on screen etc., may be independent of fbs. For instance, you might have a library that draws nice graphs using PyQt APIs. That wouldn't be _based on_ (to use the GPL phrase) fbs, and thus would not fall under its license requirements.

But say you're writing Microsoft Excel with fbs and split it into `main.py` and `library` as above, where the latter is "a general-purpose library for displaying spreadsheets". If `library` is used nowhere else, by no other product or organization, and the fbs-based binary is one of the (if not the) main form in which people use your app, would you say `library` is _not_ based on fbs? Of course it's not black and white. But I think it would be difficult to justify such reasoning.

As I understand it, that's basically the point made by the [FAQ entry about Interpreters](https://www.gnu.org/licenses/gpl-faq.html#IfInterpreterIsGPL) of the GPL. fbs basically acts as an interpreter because it runs your app. If your app were just data blindly read by fbs, maybe not even a GUI app, then the GPL FAQ argues that you could not be made subject to the terms of the GPL. But(!) fbs apps rely on very specific infrastructure to be present, such as the `QApplication` created by fbs. In the interpreter example, this is called a binding / facility, and the FAQ argues that relying on it absolutely makes you subject to the terms of the GPL. Hence I would argue that the same applies to fbs apps.

Would love to hear what you think! You proved me wrong once. It's not unlikely I've just given you an opportunity to do it again. If you find flaws in my reasoning, please do let me know where they are.

Many thanks,
Michael

**Comment by hansfilipelo** [comment]
First I'd like to say that I have no intent of sounding harsh when writing, I'm just trying to make my point. I hope that you, whichever license you may choose to continue with, do not have trouble with your license. 

---------

> Do I assume correctly that in your scenario, `closedsourcethirdpartylib` depends on PyQt, but not on fbs?

Well no library really depends on fbs is my point. That a library depends on QApplication means it depends on PyQt. 

> 
> As a side note, what you wrote above is not entirely correct:
> 
> > fbs instead packages independent software into a distribution.
> 
> It also _runs_ your application. In other words, parts of fbs are contained in the binary package produced by fbs. These parts thus become an integral part of your application.

Linux, for example, is GPL (not LGPL) and it runs many applications which are not GPL, some of which can _only_ run on Linux (though should be said that this is GPLv2). 

> Let me call the issue you are describing "loophole". I know you don't mean it that way - you are more concerned about the legal ramifications for other libraries. But from fbs's perspective that's where the threat lies.

A lot of loopholes in GPL in order for non-GPL apps to run on Linux. In my view this is not a loophole since it is widespread, I'd consider it an incorrect interpretation of GPL for the sake of fbs here. 

> But say you're writing Microsoft Excel with fbs and split it into `main.py` and `library` as above, where the latter is "a general-purpose library for displaying spreadsheets". If `library` is used nowhere else, by no other product or organization, and the fbs-based binary is one of the (if not the) main form in which people use your app, would you say `library` is _not_ based on fbs? Of course it's not black and white. But I think it would be difficult to justify such reasoning.
> 
> As I understand it, that's basically the point made by the [FAQ entry about Interpreters](https://www.gnu.org/licenses/gpl-faq.html#IfInterpreterIsGPL) of the GPL. fbs basically acts as an interpreter because it runs your app. If your app were just data blindly read by fbs, maybe not even a GUI app, then the GPL FAQ argues that you could not be made subject to the terms of the GPL. But(!) fbs apps rely on very specific infrastructure to be present, such as the `QApplication` created by fbs. In the interpreter example, this is called a binding / facility, and the FAQ argues that relying on it absolutely makes you subject to the terms of the GPL. Hence I would argue that the same applies to fbs apps.

As I understand the design of fbs, no library would need to specifically depend on the QApplication created by fbs but rather any QApplication created by PyQt. Here's a quote from the GPL FAQ on intepreters:

> However, when the interpreter is extended to provide “bindings” to other facilities (often, but not necessarily, libraries), the interpreted program is effectively linked to the facilities it uses through these bindings. So if these facilities are released under the GPL, the interpreted program that uses them must be released in a GPL-compatible way. The JNI or Java Native Interface is an example of such a binding mechanism; libraries that are accessed in this way are linked dynamically with the Java programs that call them. These libraries are also linked with the interpreter. If the interpreter is linked statically with these libraries, or if it is designed to link dynamically with these specific libraries, then it too needs to be released in a GPL-compatible way

The "bindings" is in this case is, again, QApplication which is PyQt. PyQt can run without GPL and with a commercial license. The library is not linked statically to fbs (it _can_ work without fbs) and fbs is not designed to run specifically "with these libraries" - Hence the library does not need to be GPL. 

-------------

I'll stop trying to convince you that GPL is the wrong choice for fbs, even if it is my strong belief that you are misinterpreting the meaning of it. I think that both of us could use our time to be more productive. You are the author of fbs and you have every right to license it under whichever license you prefer.

**Comment by mherrmann** [comment]
No offense taken. The Linux API is exempt from the GPL for precisely the reason you mention. So (also not wanting to sound harsh) I don't think it's a valid example.

> The "bindings" is in this case is, again, QApplication which is PyQt.

I would argue the bindings are QApplication/PyQt and fbs is the "facilities". 

If a library can work without fbs, realistically and not just theoretically, then I agree it's not bound by the GPL.

Unless you want to continue the discussion, I'm happy to leave it at that. Again, thank you very much for your inputs.
